name: dolaNow
description: A new Flutter project.

version: 1.1.0+2.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  http:
  page_transition: ^1.1.7+2
  liquid_progress_indicator: ^0.3.2
  splashscreen: ^1.3.3
  gradient_text: ^1.0.2
  flutter_launcher_icons: ^0.8.1
  firebase_admob: ^0.10.3
  firebase_core: ^0.5.3
  fl_chart: ^0.12.2
  lottie: ^0.7.0+1
  get: ^4.1.4
  auto_size_text: ^2.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/Title.png
    - assets/Dolar.png
    - assets/bg.jpg
    - assets/sort.png
    - assets/convert.png
    - assets/home.png
    - assets/arrow.png
    - assets/Dola_Animation.json
    - assets/load.json


  fonts:
    - family: Jaapokki
      fonts:
        - asset: fonts/jaapokki-regular.ttf
    - family: RobotoBold
      fonts:
        - asset: fonts/Roboto-Bold.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Light.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icone.png"